### ISSUE TITLE
Indentation incorrect level for chained method with bracket on new line

### ISSUE THREAD

**Issue by olivierGuillermEkino** [ekino/gradle-quality-plugin#5]
Example:
`
assertThat(result)
                .containsOnly(     // <- this is at level 16
                        tuple(ID_1, expectedField2, expectedField3),
                        tuple(ID_2, expectedField2, expectedField3)
                );                          // <- 'method call rparen' has incorrect indentation level 16, expected level should be 8. [Indentation]
`

https://github.com/checkstyle/checkstyle/issues/6210

Checkstyle 8.19 is not compliant with actual Codestyle.xml
Codestyle cannot be adapt to this rule

**Comment by clemstoquart** [comment]
Hi @olivierGuillermEkino 

Is this issue still relevant ?

**Comment by olivierGuillermEkino** [comment]
Issue deprecated
